### ISSUE TITLE
Uploading

### ISSUE THREAD

**Issue by oskarrough** [HappySale/ember-cli-cloudinary-images#1]
Thanks so much for this. Do you have any code examples for how to handle uploads?

**Comment by oriSomething** [comment]
thank you. but this addon doesn't includes upload... because:
- it suppose to be in different addon (don't want to force people download things they don't need)
- should uploader suppose to support drag & drop?
- should uploader suppose to show preview before uploading? maybe cropping options? (and previews are also slow and making them means very narrow browser support, no old IE / android)
- how the preview should look like?
- should uploader suppose to give the user manual options?
- should it upload right away, or only when there is a confirmation from the user?
- what is the strategy you're using to protect from everyone to spam your account?

maybe, we can still create an addon that can solve well most of the problem, and still its place is in different addon, and then the name will be `ember-cli-cloudinary-uploader` ;)
anyway, right now, we use a custom uploader, but it tight to our system and made for a very edge case, so it cannot be open source in its current form.
for getting better understanding about the `server` side for picking strategy, look at [cloudinary_parse](https://github.com/cloudinary/cloudinary_parse).

however this addon, will get more updates, to make it more useful. (there are a few things that needs support, maybe also getting the best cdn URL for example).

sorry, this answer long… very long.

**Comment by oskarrough** [comment]
Yea, I understand. I managed to get upload working for our app now and will see if it makes sense to publish it as a more general ember-cloudinary-uploader! Thank you again.
